### ISSUE TITLE
Random considerations

### ISSUE THREAD

**Issue by xaur** [xaur/decred-news#1]
Some things I considered but couldn't decide. Let's branch any non-trivial discussion to separate issues.

- [x] Keep quotes of people or rewrite to minimze text and streamline style?
  => moved to #3
- [x] Events
  - [x] Consistent structured format (title, date, city, country, people) vs free float?
    => [June 2018](https://github.com/xaur/decred-news/blob/master/journal/201806.md) issue has settled on a reasonable format.
  - [x] Use table (boring?)?
    => No, don't use tables
- [x] Group paragraphs by topic: introduce 3rd level headings or start paragraphs with bold first words?
  => moved to #24
- [x] Always mention people who made/reported/announced something?
  => Mixed, not strict.
- [x] Always put (source) after quote?
  => Yes
- [x] Always prepend author in quote?
  => No, put author name in parens after the quote
- [x] Use "we", "our", "us", etc?
  => moved to #93 
- [x] Use "I"?
  => moved to #93 
- [x] Level of detail: Shorter version for newsletter?
  => moved to #4

**Comment by xaur** [comment]
> jazzah: I guess it would be nice to have a column for locations and one for exact dates. You could also end that paragraph with a link to our page listing future events. (not sure if one exists yet)

**Comment by Arriu** [comment]
Hey, this is Jazzah.
I think I answered questions 1 and 4-8 on slack yesterday:

I guess the main concern with this format is the fact that it is less slick/streamlined. Also it may be confusing to people who have never heard about all the individuals mentioned. Nevertheless, I really like the way you did it, mentioning source material as often as you can, this is a practice sorely lacking generally today imo
it also emphasizes the community to me , rather than all the info seemingly coming from an abstract decentralized organization. 

To add to that: Showing that the community is made up by individuals like you and me and giving credit where it is due, rather than presenting everything from the impersonal 'we', may make it less daunting for outsiders to join in 

Question 3:
i prefer the bold suggestion over additional subtitles.
Last Question:
I don't think there is the need for a shorter format, because your structure is good, so people can just skim through it and quickly get to the info they want, disregarding what they are not interested in.

**Comment by xaur** [comment]
@Arriu thanks for posting feedback right here! For the purpose of organizing feedback I quoted you in more specific issues #3 and #4.

**Comment by xaur** [comment]
> i prefer the bold suggestion over additional subtitles.
@Arriu check this prototype https://github.com/xaur/decred-news/blob/bold/posts/201804.md

**Comment by xaur** [comment]
Always put (source) after quote? => Yes.

Always prepend author in quote? => No, try to always use the standard format `> text (@author on source)`
